version: '3.3'

networks:
  kong-net:
    name: kong-net
    driver: bridge
    external: true

services:
  transactions-api:
    build: .
    container_name: transactions-api
    networks:
      - kong-net
    ports:
      - 3003:3003
    volumes:
      - .:/go/src/app
    env_file:
      - .env
